### ISSUE TITLE
Specs using frozen string literals fail

### ISSUE THREAD

**Issue by kimburgess** [acaprojects/ruby-engine#10]
When using a module spec with immutable strings (i.e. from `frozen_string_literal` magic comment) an error is thrown.

```
07/11/2017 @ 06:37PM ERROR: [mod-testing] error tokenizing data. Clearing buffer..
can't modify frozen String
/usr/local/bundle/gems/uv-rays-2.2.2/lib/uv-rays/buffered_tokenizer.rb:54:in `force_encoding'
/usr/local/bundle/gems/uv-rays-2.2.2/lib/uv-rays/buffered_tokenizer.rb:54:in `extract'
/home/aca-apps/ruby-engine/lib/orchestrator/device/processor.rb:196:in `buffer'
/home/aca-apps/ruby-engine/lib/orchestrator/testing/mock_transport.rb:55:in `receive'
/home/aca-apps/ruby-engine/lib/orchestrator/testing/mock_device.rb:108:in `transmit'
/home/aca-apps/aca-device-modules/modules/sony/display/bravia_spec.rb:7:in `block in <top (required)>'
/home/aca-apps/ruby-engine/lib/orchestrator/testing/mock_device.rb:63:in `instance_exec'
/home/aca-apps/ruby-engine/lib/orchestrator/testing/mock_device.rb:63:in `block in mock_device'
/usr/local/bundle/gems/libuv-3.2.2/lib/libuv/reactor.rb:174:in `block in run'
/usr/local/bundle/gems/libuv-3.2.2/lib/libuv/fiber_pool.rb:19:in `block in exec'
/usr/local/bundle/gems/libuv-3.2.2/lib/libuv/fiber_pool.rb:76:in `block (2 levels) in new_fiber'
/usr/local/bundle/gems/libuv-3.2.2/lib/libuv/fiber_pool.rb:73:in `loop'
/usr/local/bundle/gems/libuv-3.2.2/lib/libuv/fiber_pool.rb:73:in `block in new_fiber'
ERROR: module did not send "*SEPOWR################\n" as expected
```

This is due to [uv-rays forcing an encoding](https://github.com/cotag/uv-rays/blob/master/lib/uv-rays/buffered_tokenizer.rb#L54) in the tokenizer, which is not idempotent. With string literals likely moving to [immutable by default in Ruby 3](https://bugs.ruby-lang.org/issues/8976#note-41) it's probably worth fixing this up (rather than just not using the `frozen_string_literal` pragma). From what I've been able to spot there's a couple of places this could happen:

1. `dup` data [in uv-rays before changing encoding](https://github.com/cotag/uv-rays/blob/master/lib/uv-rays/buffered_tokenizer.rb#L54) *(probably not good for performance of real devices)*
2. `dup` in [mock_device#transmit](https://github.com/acaprojects/ruby-engine/blob/master/lib/orchestrator/testing/mock_device.rb#L105)
3. ...or in [mock_transport#recieve](https://github.com/acaprojects/ruby-engine/blob/master/lib/orchestrator/testing/mock_transport.rb#L55)

I'm not familiar enough with the overall data flow to make a call on what's best, but happy to submit a PR based on your yoda like advice @stakach :)

**Comment by stakach** [comment]
Hmm I'm actually thinking it's best done in the buffer `String.new(data).force_encoding(@encoding)`

**Comment by stakach** [comment]
Actually you are right with the mock transport / device - as we'd probably have noticed an error about modifying frozen string literals on production and no point wasting the memory

**Comment by kimburgess** [comment]
Yep, AFAIK the v3 change is for string literals only (see [this discussion from Matz](https://twitter.com/yukihiro_matz/status/634386185507311616)) so shouldn't effect data coming from real devices, just mock data that's been defined as a literal.
