### ISSUE TITLE
Add a basic version control to systems and zones

### ISSUE THREAD

**Issue by stakach** [acaprojects/ruby-engine#4]
Devices / logic modules would be harder to version control and should be easy enough to restore - this means when a **deleted** system is restored, it will contain no devices except those shared with other systems as the devices. Undoing a change would not suffer from this.

Previous versions of systems could be saved as `"backup1-#{system.id}"`, `"backup2-#{system.id}"`, alternating between them.

Backups would have a sunset period to ensure the database is not cluttered. i.e. 2 weeks before automatically being destroyed by the database.

**Comment by kimburgess** [comment]
Closing out this zombie issue as a “will-not-do” for this project. Implementation of similar functionality available in the current iteration of the platform (https://github.com/placeos).
